WebApplication1/WebApplication1/Models/PersonalTrainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    [Table("Personal_trainer")]
    public partial class PersonalTrainer
    {
        [Key]
        [Column("IDProfessor")]
        public int Idprofessor { get; set; }
        [Key]
        [Column("IDSocio")]
        public int Idsocio { get; set; }
        [Key]
        [Column("Data_Pedido", TypeName = "date")]
        public DateTime DataPedido { get; set; }
        [Column("data_Inicio", TypeName = "date")]
        public DateTime? DataInicio { get; set; }
        [Column("data_fim", TypeName = "date")]
        public DateTime? DataFim { get; set; }

        [ForeignKey(nameof(Idprofessor))]
        [InverseProperty(nameof(Professores.PersonalTrainer))]
        public virtual Professores IdprofessorNavigation { get; set; }
        [ForeignKey(nameof(Idsocio))]
        [InverseProperty(nameof(Socios.PersonalTrainer))]
        public virtual Socios IdsocioNavigation { get; set; }
    }
}

WebApplication1/WebApplication1/Controllers/SociosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using WebApplication1.filters;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{

    public class SociosController : Controller
    {
        private readonly GinasioContext _context;

        private readonly IHostEnvironment _hostEnviroment;

        public SociosController(GinasioContext context, IHostEnvironment env)
        {
            _context = context;
            _hostEnviroment = env;
        }

        // GET: Socios
        public async Task<IActionResult> Index()
        {
            ViewBag.userId = HttpContext.Session.GetInt32("UserId");
            ViewBag.Nome = HttpContext.Session.GetString("Nome");
            return View(await _context.Socios.ToListAsync());
        }

        public async Task<IActionResult> ListarSociosAdmin()
        {
            ViewBag.userId = HttpContext.Session.GetInt32("UserId");
            ViewBag.Nome = HttpContext.Session.GetString("Nome");
            return View(await _context.Socios.ToListAsync());
        }


        // GET: Socios/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var socios = await _context.Socios
                .FirstOrDefaultAsync(m => m.Idsocio == id);
            if (socios == null)
            {
                return NotFound();
            }

            return View(socios);
           
            


            //if((professores.Idprofessor== personal.Idprofessor) & (socios.Idsocio == personal.Idsocio))
            //{
            //   //return
            //}
            //else
            //{
            //    //return ("Details");
            //}
        }

        public async Task<IActionResult> EditarEstadoSocio(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var socios = await _context.Socios.FindAsync(id);
            if (socios == null)
            {
                return NotFound();
            }
            return View(socios);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> EditarEstadoSocio(int id, [Bind("Idsocio,Email,Telefone,Fotografia,Sexo,Altura,NomeUtilizador,PesoInicial,Password,Estado")] Socios socios, IFormFile fotografia)
        {
            string caminho = Path.Combine(_hostEnviroment.ContentRootPath, "wwwroot\\Fotos");

            string nome_ficheiro = Path.GetFileName(fotografia.FileName);
            string caminho_completo = Path.Combine(caminho, nome_ficheiro);

            FileStream fs = new FileStream(caminho_completo, FileMode.Create);
            fotografia.CopyTo(fs);
            socios.Fotografia = nome_ficheiro;


            fs.Close();
            if (id != socios.Idsocio)
            {
                return NotFound();
            }




            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(socios);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SociosExists(socios.Idsocio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(socios);
        }

        public async Task<IActionResult> ListarSocios()
        {
            ViewBag.userId = HttpContext.Session.GetInt32("UserId");
            ViewBag.Nome = HttpContext.Session.GetString("Nome");
            return View(await _context.Socios.ToListAsync());
        }


        public IActionResult PerfilSocio(int? id)
        {
            int x = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));


            foreach (var item in _context.Socios)
            {
                if (item.Idsocio == x)
                {
                    var y = item;
                    return View(y);

                }
            }


            return View();
        }




        //public IActionResult  EfetuarPagamento()
        //{
        //    int x = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));


        //    foreach (var item in _context.Socios)
        //    {
        //        if (item.Idsocio == x)
        //        {
        //            var y = item;
        //            return View(y);

        //        }
        //    }
        //    return View();
        //}

       





        public IActionResult RegistarSocio()
        {
            return View();
        }





        // POST: Socios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegistarSocio([Bind("Idsocio,Email,Telefone,Fotografia,Sexo,Altura,NomeUtilizador,PesoInicial,Password,Estado")] Socios socios, IFormFile fotografia/*,Professores professores*//*,Administrador administrador*/)
        {
            ////verifica se o nome e o email ja existem
            //foreach (var item in _context.Socios)
            //{
            //    if ((administrador.Nome == item.NomeUtilizador) || (administrador.Email == item.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }



            //}

            //foreach (var item2 in _context.Administrador)
            //{
            //    if ((administrador.Nome == item2.Nome) || (administrador.Email == item2.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }


            //}


            //foreach (var item3 in _context.Professores)
            //{
            //    if ((administrador.Nome == item3.Nome) || (administrador.Email == item3.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }

            //}
            ////para os socios
            //foreach (var item4 in _context.Socios)
            //{
            //    if ((socios.NomeUtilizador == item4.NomeUtilizador) || (socios.Email == item4.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }



            //}

            //foreach (var item5 in _context.Administrador)
            //{
            //    if ((socios.NomeUtilizador == item5.Nome) || (socios.Email == item5.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }


            //}

            //foreach (var item6 in _context.Professores)
            //{
            //    if ((socios.NomeUtilizador == item6.Nome) || (socios.Email == item6.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }

            //}

            ////para os professores
            //foreach (var item7 in _context.Socios)
            //{
            //    if ((professores.Nome == item7.NomeUtilizador) || (professores.Email == item7.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }

            //}

            //foreach (var item8 in _context.Administrador)
            //{
            //    if ((professores.Nome == item8.Nome) || (professores.Email == item8.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }


            //}

            //foreach (var item9 in _context.Professores)
            //{
            //    if ((administrador.Nome == item9.Nome) || (administrador.Email == item9.Email))
            //    {
            //        ViewBag.MsgError = "Utilizador já está registado no sistema.";
            //        //return View("Registo");
            //    }

            //}
            string caminho = Path.Combine(_hostEnviroment.ContentRootPath, "wwwroot\\Fotos");

            string nome_ficheiro = Path.GetFileName(fotografia.FileName);
            string caminho_completo = Path.Combine(caminho, nome_ficheiro);

            FileStream fs = new FileStream(caminho_completo, FileMode.Create);
            fotografia.CopyTo(fs);
            socios.Fotografia = nome_ficheiro;


            fs.Close();


            if (ModelState.IsValid)
            {


                _context.Add(socios);
                await _context.SaveChangesAsync();
                return RedirectToAction("Login", "Home");
            }
            return View(socios);
        }



        // GET: Socios/Edit/5

        public async Task<IActionResult> EditarDadosSocio(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var socios = await _context.Socios.FindAsync(id);
            if (socios == null)

WebApplication1/WebApplication1/Views/PersonalTrainers/Create.cshtml
@model WebApplication1.Models.PersonalTrainer

@{
    ViewData["Title"] = "Create";
}
    <style>
        body {
            padding-top: 0px;
            background-color: gray;
            background-image: url();
            background-image: url();
            background-repeat: no-repeat;
        }
    </style>


<h4 style="color:white">Criar Personal Trainer</h4>
<hr />
<div class="row" style="color:white">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" disabled="disabled"  class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar < </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/PersonalTrainers/Delete.cshtml
@model WebApplication1.Models.PersonalTrainer

@{
    ViewData["Title"] = "Delete";
}

    <style>
        body {
            padding-top: 0px;
            background-color: gray;
            background-image: url();
            background-image: url();
            background-repeat: no-repeat;
        }
    </style>

<h3 style="color:red"> Quer Apagar este personal trainer ? </h3>
<div style="color:white">
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdprofessorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdprofessorNavigation.Email)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdsocioNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdsocioNavigation.Email)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Idprofessor" />
        <input type="hidden" asp-for="Idsocio" />
        <input type="hidden" asp-for="DataPedido" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index"> Voltar <</a>
    </form>
</div>

WebApplication1/WebApplication1/Views/PersonalTrainers/Details.cshtml
@model WebApplication1.Models.PersonalTrainer

@{
    ViewData["Title"] = "Details";
}
    <style>
        body {
            padding-top: 0px;
            background-color: gray;
            background-image: url();
            background-image: url();
            background-repeat: no-repeat;
        }
    </style>


<div style="color:white">
    <h4 style="color:white">Detalhes do Personal seu Trainer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdprofessorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdprofessorNavigation.Email)
        </dd>
        
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Voltar <</a>
</div>

WebApplication1/WebApplication1/Views/PersonalTrainers/Edit.cshtml
@model WebApplication1.Models.PersonalTrainer

@{
    ViewData["Title"] = "Edit";
}

    <style>
        body {
            padding-top: 0px;
            background-color: gray;
            background-image: url();
            background-image: url();
            background-repeat: no-repeat;
        }
    </style>

<h4 style="color:white"> Dados - Adotou este  Personal Trainer : </h4>
<hr />
<div class="row" style="color:white">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idprofessor" />
            <input type="hidden" asp-for="Idsocio" />
            <input type="hidden" asp-for="DataPedido" />
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label">Data Inicio :</label>
                <input asp-for="DataInicio" disabled="disabled"   class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label">Data Fim :</label>
                <input asp-for="DataFim" disabled="disabled"  class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar <</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/PersonalTrainers/Index.cshtml
@model IEnumerable<WebApplication1.Models.PersonalTrainer>

@{
    ViewData["Title"] = "Index";
}

    <style>
        body {
            padding-top: 0px;
            background-color: gray;
            background-image: url();
            background-image: url();
            background-repeat: no-repeat;
        }
    </style>

<table class="table" style="color:white">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DataInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataFim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdprofessorNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdsocioNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DataInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataFim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdprofessorNavigation.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdsocioNavigation.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication1/WebApplication1/Views/PersonalTrainers/VerPT.cshtml
@model WebApplication1.Models.PersonalTrainer

@{
    ViewData["Title"] = "VerPT";
}


<style>
    body {
        padding-top: 0px;
        background-color: darkgray;
        background-image: url();
        background-image: url();
        background-repeat: no-repeat;
    }
</style>

<div>
    <h4>Personal Trainer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Data de inicio :
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>

        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdprofessorNavigation.Email)
        </dd>

    </dl>
</div>
<div>

    <a asp-action="PerfilSocio" asp-controller="Socios">Voltar</a>
</div>